# Generated by Django 6.0.4 on 2026-04-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Competition'},
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
