# Generated by Django 6.0.4 on 2026-04-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_code_product_sku_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
