# Generated by Django 6.0.4 on 2026-04-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_store_created_at_remove_store_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
